[build]
  publish = "dist/public"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://server.x-host.cloud:25539/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/assets/*"
  to = "https://server.x-host.cloud:25539/assets/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
