[build]
  publish = "dist/public"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://panel.arabdevs.xyz/server/aa10fd22/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/assets/*"
  to = "https://panel.arabdevs.xyz/server/aa10fd22/assets/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
